# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [public]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Installing my packages
        run: yarn install --frozen-lockfile

      - name: Build my App
        run: yarn run build && yarn run export && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
          RINKEBY_RPC_URL: ${{ secrets.RINKEBY_RPC_URL }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          UPDATE_FRONT_END: ${{ secrets.UPDATE_FRONT_END }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          BSC_TESTNET_RPC_URL: ${{ secrets.BSC_TESTNET_RPC_URL }}
          AVALANCHE_TESTNET_RPC_URL: ${{ secrets.AVALANCHE_TESTNET_RPC_URL }}
          AVALANCHE_TESTNET_PRIVATE_KEY: ${{ secrets.AVALANCHE_TESTNET_PRIVATE_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          NEXT_PUBLIC_SIGNER_PK: ${{ secrets.NEXT_PUBLIC_SIGNER_PK }}
          NEXT_PUBLIC_DEPLOYER_PK: ${{ secrets.NEXT_PUBLIC_DEPLOYER_PK }}
          NEXT_PUBLIC_FAUNA_SECRET: ${{ secrets.NEXT_PUBLIC_FAUNA_SECRET }}
          NEXT_PUBLIC_JWT_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_RECAPTCHA_SECRET: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET }}
          NEXT_PUBLIC_RECAPTCHA_SITEKEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITEKEY }}
          BRANCH: public # The branch the action will deploy to
          FOLDER: out # The folder the action will deploy to
